//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_workspace
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnakeLeaderboardDBEntities : DbContext
    {
        public SnakeLeaderboardDBEntities()
            : base("name=SnakeLeaderboardDBEntities")
        {
        }

        private static SnakeLeaderboardDBEntities _instance;
        public static SnakeLeaderboardDBEntities Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = new SnakeLeaderboardDBEntities();
                }
                return _instance;
            }
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Leaderboard> Leaderboard { get; set; }
    }
}
