//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_workspace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaderboard
    {
        public string PlayerName { get; set; }
        public int PlayerScore { get; set; }
    }
}
